const admin = require("firebase-admin");
const serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

const seedData = [
  {
    status: "active",
    commodity: "Coconut",
    variety: "Virgin White",
    quantity_mt: 500,
    est_price: 230.00,
    coop_name: "Matale Coconut Co-op",
    origin: "Matale, Sri Lanka",
    fob_port: "Colombo, Sri Lanka",
    sellerId: "SELLER_UID_1",
    sellerEmail: "matale@coop.lk",
    sellerPhone: "+94 11 234 5678",
    grade: "A",
    bid_count: 0,
    remaining_mt: 500,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Coffee",
    variety: "Arabica",
    quantity_mt: 200,
    est_price: 185.00,
    coop_name: "Ethiopian Highlands Co-op",
    origin: "Sidamo, Ethiopia",
    fob_port: "Djibouti",
    sellerId: "SELLER_UID_2",
    sellerEmail: "sidamo@coop.et",
    sellerPhone: "+251 11 551 2345",
    grade: "AA",
    bid_count: 0,
    remaining_mt: 200,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Cocoa",
    variety: "Forastero",
    quantity_mt: 300,
    est_price: 2850.00,
    coop_name: "Ghana Cocoa Board Co-op",
    origin: "Kumasi, Ghana",
    fob_port: "Tema, Ghana",
    sellerId: "SELLER_UID_3",
    sellerEmail: "kumasi@coop.gh",
    sellerPhone: "+233 30 276 1234",
    grade: "Grade 1",
    bid_count: 0,
    remaining_mt: 300,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Vanilla",
    variety: "Bourbon",
    quantity_mt: 50,
    est_price: 65.00,
    coop_name: "Madagascar Vanilla Alliance",
    origin: "Sambava, Madagascar",
    fob_port: "Toamasina, Madagascar",
    sellerId: "SELLER_UID_4",
    sellerEmail: "sambava@coop.mg",
    sellerPhone: "+261 20 22 123 45",
    grade: "Grade A",
    bid_count: 0,
    remaining_mt: 50,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Cashews",
    variety: "W320",
    quantity_mt: 150,
    est_price: 3.22,
    coop_name: "Ivory Coast Nut Co-op",
    origin: "Korhogo, Ivory Coast",
    fob_port: "Abidjan, Ivory Coast",
    sellerId: "SELLER_UID_5",
    sellerEmail: "korhogo@coop.ci",
    sellerPhone: "+225 20 30 40 50",
    grade: "W320",
    bid_count: 0,
    remaining_mt: 150,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Rice",
    variety: "Basmati",
    quantity_mt: 1000,
    est_price: 450.00,
    coop_name: "Punjab Rice Growers",
    origin: "Lahore, Pakistan",
    fob_port: "Karachi, Pakistan",
    sellerId: "SELLER_UID_6",
    sellerEmail: "lahore@coop.pk",
    sellerPhone: "+92 42 1234 5678",
    grade: "Extra Long",
    bid_count: 0,
    remaining_mt: 1000,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Turmeric",
    variety: "Alleppey",
    quantity_mt: 80,
    est_price: 1.85,
    coop_name: "Kerala Spice Collective",
    origin: "Alleppey, India",
    fob_port: "Cochin, India",
    sellerId: "SELLER_UID_7",
    sellerEmail: "alleppey@coop.in",
    sellerPhone: "+91 477 123 4567",
    grade: "Finger",
    bid_count: 0,
    remaining_mt: 80,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Black Pepper",
    variety: "Malabar",
    quantity_mt: 120,
    est_price: 2.95,
    coop_name: "Kerala Pepper Board",
    origin: "Wayanad, India",
    fob_port: "Cochin, India",
    sellerId: "SELLER_UID_8",
    sellerEmail: "wayanad@coop.in",
    sellerPhone: "+91 4936 123 456",
    grade: "MG1",
    bid_count: 0,
    remaining_mt: 120,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Cinnamon",
    variety: "Ceylon",
    quantity_mt: 60,
    est_price: 3.45,
    coop_name: "Sri Lanka Spice Exporters",
    origin: "Galle, Sri Lanka",
    fob_port: "Colombo, Sri Lanka",
    sellerId: "SELLER_UID_1",
    sellerEmail: "galle@coop.lk",
    sellerPhone: "+94 91 222 3333",
    grade: "Alba",
    bid_count: 0,
    remaining_mt: 60,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Coconut Oil",
    variety: "Cold Pressed",
    quantity_mt: 200,
    est_price: 1.25,
    coop_name: "Philippine Coconut Authority",
    origin: "Davao, Philippines",
    fob_port: "Manila, Philippines",
    sellerId: "SELLER_UID_9",
    sellerEmail: "davao@coop.ph",
    sellerPhone: "+63 82 123 4567",
    grade: "VCO",
    bid_count: 0,
    remaining_mt: 200,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Mangoes",
    variety: "Alphonso",
    quantity_mt: 100,
    est_price: 1.18,
    coop_name: "Ratnagiri Mango Growers",
    origin: "Ratnagiri, India",
    fob_port: "Mumbai, India",
    sellerId: "SELLER_UID_10",
    sellerEmail: "ratnagiri@coop.in",
    sellerPhone: "+91 2353 123 456",
    grade: "Export",
    bid_count: 0,
    remaining_mt: 100,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Soybeans",
    variety: "Non-GMO",
    quantity_mt: 500,
    est_price: 520.00,
    coop_name: "Iowa Soybean Association",
    origin: "Des Moines, USA",
    fob_port: "New Orleans, USA",
    sellerId: "SELLER_UID_11",
    sellerEmail: "desmoines@coop.us",
    sellerPhone: "+1 515 123 4567",
    grade: "No. 2 Yellow",
    bid_count: 0,
    remaining_mt: 500,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Ginger",
    variety: "Young",
    quantity_mt: 70,
    est_price: 0.95,
    coop_name: "Nigerian Ginger Farmers",
    origin: "Kaduna, Nigeria",
    fob_port: "Lagos, Nigeria",
    sellerId: "SELLER_UID_12",
    sellerEmail: "kaduna@coop.ng",
    sellerPhone: "+234 62 123 4567",
    grade: "A",
    bid_count: 0,
    remaining_mt: 70,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Palm Oil",
    variety: "Crude",
    quantity_mt: 1000,
    est_price: 0.85,
    coop_name: "Malaysian Palm Oil Board",
    origin: "Kuala Lumpur, Malaysia",
    fob_port: "Port Klang, Malaysia",
    sellerId: "SELLER_UID_13",
    sellerEmail: "kl@coop.my",
    sellerPhone: "+60 3 1234 5678",
    grade: "CPKO",
    bid_count: 0,
    remaining_mt: 1000,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Almonds",
    variety: "Nonpareil",
    quantity_mt: 250,
    est_price: 6.48,
    coop_name: "California Almond Growers",
    origin: "Modesto, USA",
    fob_port: "Oakland, USA",
    sellerId: "SELLER_UID_14",
    sellerEmail: "modesto@coop.us",
    sellerPhone: "+1 209 123 4567",
    grade: "Supreme",
    bid_count: 0,
    remaining_mt: 250,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Wheat",
    variety: "Hard Red Winter",
    quantity_mt: 800,
    est_price: 280.00,
    coop_name: "Kansas Wheat Commission",
    origin: "Wichita, USA",
    fob_port: "Houston, USA",
    sellerId: "SELLER_UID_15",
    sellerEmail: "wichita@coop.us",
    sellerPhone: "+1 316 123 4567",
    grade: "No. 2 HRW",
    bid_count: 0,
    remaining_mt: 800,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Peanuts",
    variety: "Runner",
    quantity_mt: 300,
    est_price: 1.24,
    coop_name: "Georgia Peanut Commission",
    origin: "Tifton, USA",
    fob_port: "Savannah, USA",
    sellerId: "SELLER_UID_16",
    sellerEmail: "tifton@coop.us",
    sellerPhone: "+1 229 123 4567",
    grade: "Runner 38/42",
    bid_count: 0,
    remaining_mt: 300,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Bananas",
    variety: "Cavendish",
    quantity_mt: 400,
    est_price: 0.52,
    coop_name: "Ecuador Banana Exporters",
    origin: "Guayaquil, Ecuador",
    fob_port: "Guayaquil, Ecuador",
    sellerId: "SELLER_UID_17",
    sellerEmail: "guayaquil@coop.ec",
    sellerPhone: "+593 4 123 4567",
    grade: "AAA",
    bid_count: 0,
    remaining_mt: 400,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Oranges",
    variety: "Valencia",
    quantity_mt: 350,
    est_price: 0.48,
    coop_name: "Florida Citrus Growers",
    origin: "Orlando, USA",
    fob_port: "Miami, USA",
    sellerId: "SELLER_UID_18",
    sellerEmail: "orlando@coop.us",
    sellerPhone: "+1 407 123 4567",
    grade: "US Fancy",
    bid_count: 0,
    remaining_mt: 350,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    status: "active",
    commodity: "Olive Oil",
    variety: "Extra Virgin",
    quantity_mt: 180,
    est_price: 5.20,
    coop_name: "Andalusian Olive Co-op",
    origin: "Jaen, Spain",
    fob_port: "Malaga, Spain",
    sellerId: "SELLER_UID_19",
    sellerEmail: "jaen@coop.es",
    sellerPhone: "+34 953 123 456",
    grade: "EVOO",
    bid_count: 0,
    remaining_mt: 180,
    fees_collected: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp()
  }
];

async function seed() {
  console.log("Seeding seller_briefs...");
  for (const data of seedData) {
    await db.collection("seller_briefs").add(data);
    console.log(`  + ${data.commodity} - ${data.coop_name}`);
  }
  console.log(`\nDone! Seeded ${seedData.length} briefs.`);
  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
